pipeline {
    agent any

    stages {
        stage('Install') {
            steps {
                echo 'Istalling dependencies...'
                sh 'npm ci'
            }
        }

        stage('Build') {
            steps {
                echo 'Building application...'
                sh 'npm run build'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'npm test -- --ci'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                sh 'npm start'
            }
        }
    }
}